AndreCarvalho-Ivrim/shared-types

workflow.config.type.ts
Reorganizar o formato das configurações de filtro.
=> refactor: reorganize filter settings forma

step.action.type.ts, step.item.integration.type.ts, step.item.view.type.ts, step.type.ts, utils/README.md, workflow.config.type.ts
- Melhorias de tipagem
- Comentários para facilitação de conhecimento dos recursos disponíveis
- Implementação de suporte a duplicidade em integração com excel
- Implementação de regras no StepAction
- **Rules em actions**
Foi adicionado a propriedade rules em actions, para que quando o usuário clicar em um action especifico de uma etapa, ele possa ter regras exclusivas para satisfação desta ação.<br/><br/>
- **ConfirmAction com apenas 2 actions**
Agora no confirm action, em vez de um array de ações é obrigatório que tenha apenas 2 ações, confirmação positiva e negativa.<br/><br/>
- **Rule.duplicity em IntegrationExcelType**
Na integração com excel é possível habilitar uma regra de controle de duplicidade, que ela seguirá a parametrização para tentar realizar matchs dos dados novos com os …
=> Feature/isa 107@refactor consignment closing

step.item.view.type.ts, workflow.config.type.ts
Criando novo tipo de autenticação para public routes, com base no flowAuth de um wf externo, e adicionando novo tipo de mascara para ViewDescription
- [step.item.view.type.ts]: Adicionado mascará progress-bar
- [workflow.config.type.ts]: Adicionado a possibilidade publicRoutes fazer request para steps, flow-datas, ou solicitar o registro autenticado caso esteja utilizando autenticação do tipo @network-flow-auth, e configurando tipagem da configuração do tipo de autenticação @network-flow-auth
- Teste manual
=> Feature/isa 307@handle igame

step.item.field.type.ts, step.item.view.type.ts, workflow.config.type.ts, workflow.entities.type.ts
Adicionado regras para lidar com recursividade, e dados adjacentes, além de configuração de um novo tipo de item, e melhorando configuração de ações do slide-over
- StepItem.autocomplete: Adicionado a possibilidade do autocomplete adicionar dados adicionais com base na opção selecionada.
- StepItem.customList: Adicionado o tipo customizado de item, lista, para adicionar um array de itens.
- ViewDescription.mask: Adicionado a mascará alert-warning
- WFActions.render_in: Adicionado slide-over
- availableFlowEntitySchema: Adicionado o tipo any ao array de tipos válidos em schema do flowEntity
- FlowEntitySchemaInfo.rules: Adicionado a rule conflit, utilizada no flowData através do WF.schema para lidar com merge de objetos recursivos
Teste manual na criação do WF-isf
=> Feature/isa 326@refector isf

report.type.ts, step.item.field.type.ts, utils/check-string-conditional.ts, utils/recursive-datas.ts, utils/routes.ts, workflow.config.type.ts, workflow.entities.type.ts
Adicionando tipagens de report, melhorando funções de acesso recursivo e de codehelpers.
- [report.type.ts]: Criando tipagem compartilhada para reports.
- [step.item.field.type.ts]: Criando tipagem StepItemCustomDataEditableTable para controlar tabela editável.
- [check-string-conditional.ts]: Adicionando a função split_params no getCodeHelpers, que trás os parametros separados
- [recursive-datas.ts]: Apliando capacidade do getRecursiveValue, permitindo que ele acesse propriedades internas de arrays e agrupe em um map.
- [workflow.config.type.ts]: Adicionando campo para receber anexo em wf.config.notifications.attachment
- [workflow.entities.type.ts]: Adicionado tipagem file ao FlowEntities
Manual na criação de reports da duzani.
Essa branch necessitou fazer o marge com a …
=> Feature/isa 346@reports

step.item.integration.type.ts, workflow.entities.type.ts
Em step.item.integration.type.ts adicionado time nas tipagem necessárias
Em workflow.entities.type.type adicionado time nas tipagem necessárias e adicionado rules, render e observer
=> Feature/ifm 100@unavailability panel

workflow.entities.type.ts
ISAC, SHT
Adicionado tipagem min na rules das entidades
=> adicionado min na rules da tipagem de entidade

step.item.view.type.ts, workflow.entities.type.ts
Adicionado permission_to_view  typagem para a visualização da comlumn de  ViewItemTable
Adicionado a regra hidden para entidades
=> IFM-135 Ocultar dados do Técnico

step.item.widget.type.ts
Desp. Externo
ISAC
ISAC-BACK
SHT
Adicionado a tipagem de exception para o widget do tipo widget-worker-thread
=> IFM-71 WF IFM externo agenda inteligente

flow_message.type.ts, workflow.config.type.ts
Ajuste em tipagem do FlowMessage
=> Ajuste em tipagem do FlowMessage

flow_message.type.ts
=> Tipagem do chatbot

step.item.widget.type.ts
Adicionar na roterização ordens por sla
ISAC
ISAC-BACK
SHT
=> IFM-147 Ordens por SLA na roteirização

flow_message.type.ts, workflow.config.triggers.type.ts
Indisponibilidade de almoço com o técnico iniciando o almoço.
**Repositórios**: ISAC front, back e shared-types
IFM-7 > IFM-140
=> Indisponibilidade de almoço com o técnico iniciando o almoço.

step.item.integration.type.ts
ISAC
ISAC-BACK
SHT
Adicionado filters para filtrar linhas das planilhas na importação
=> IFM-163 - Adicionar Ordens do Zeus (Atividade cabista)

workflow.config.type.ts
Na etapa “Aguardando Ficha do Fornecedor“ o sistema deve EXCLUIR as fichas com mais de 10 dias fora do SLA.
ISAC
ISAC-BACK
SHT
Adicionado descriptions para adicionar no history nas rotinas do manage-flow
=> IVR-109 - Exclusão automática

flow_log.type.ts, utils/routes.ts
ISAC
ISAC-BACK
SHT
Aficionado a tipagem do flowLog
Adicionados rota da visualização do flowLog
=> ISAC-611 - Tela do FlowLogs

step.item.widget.type.ts, workflow.config.type.ts
ISAC
ISAC-BACK
SHT
Adicionado exception_views para visualização de páginas (componentes) no workflow
Adicionado o ifm-anticipation para roteirização de antecipação
=> IFM-44 - Antecipação

step.item.field.type.ts
Melhoria no campo de lojas e visualização
ISAC
SHT
Adicionado em settigns do @editable-table uma opção para não permitir seleciona uma opção já selecionada
=> IVR-112 - Stores

step.item.widget.type.ts
ISAC
ISAC-BACK
SHT
Adicionado query_tertiary no widget-worker-thread
Adicionado step_primary e step_secondary no widget-worker-thread para pegar id de etapas dentro do workerThread
=> IFM-179 - Área de Transbordo em ordens já alocadas

step.item.integration.type.ts
=> IFM-176 - Tirar Ordens "NÃO ANTECIPA" da roteirização

workflow.config.type.ts
adicionado a tipagem unavailability para resetar o verification_date das indisponibilidades do IFM
=> IFM-100 - Reset de indisponibilidades

step.item.field.type.ts
adicionado opção de expandir group-collapse
=> IVR-143 -  Campos Obrigatórios + 

workflow.config.rules.type.ts
Adicionado tipagem para adicionar valores undefined no formatters
ISAC
SHT
Task: [IVR-155](https://covabra.atlassian.net/browse/IVR-155)
=> IVR-155 - Adicionado formatters no wf isi-covabra

step.type.ts
Task: [IVR-146](https://covabra.atlassian.net/browse/IVR-146)
ISAC, SHT
Adicionado tipagem do @form-was-modified
=> IVR-146 - Checagem se teve alteração no formulario

step.item.field.type.ts
Task: [IVR-164](https://covabra.atlassian.net/browse/IVR-164)
- Adicionado a regra switch_render aos items do workflow
=> IVR-164 - Problema na renderização dos group-colapse

workflow.config.events.type.ts
Integração via conexão com o banco de dados no wf jurídico.
Repositórios: isac front, back e shared
=> Integração via conexão com o banco de dados no wf jurídico

flow_message.type.ts, step.type.ts, utils/check-string-conditional.ts
Adicionando propriedades: condition, sole_owner e lidando com afirmação e negação no operador filled do strc
=> Feature/ifm 221@create wf ability

utils/routes.ts, workflow.config.type.ts, workflow.type.ts
Criando tipagem WorkflowConfigOpenDialogType e adicionando configurações de rota do open-dialog
=> Feature/ifm 223@webchat

flow_message.type.ts, step.item.widget.type.ts
Adicionando open-dialog no flow-message
=> Feature/ifm 100@start chat

workflow.config.triggers.type.ts
Ajuste na tipagem usada nas functions do wf de agendamento
Repositórios: isac front, back e shared
=> Ajuste na tipagem usada nas functions do wf de agendamento

utils/check-field-type.ts
Formatação da data no scheduling.
Repositórios: isac front, back e shared types.
=> Formatação da data no scheduling

step.item.field.type.ts, utils/check-string-conditional.ts
Adicionado suporte ao componente StepItemCustomDataNumberWithUnitOfMeasurement
=> IFM-180 - Medidas, Novo componente

workflow.config.events.type.ts
Ajuste na tipagem do sendWhatsappMessagesEvent.
Repositórios: isac front, back e shared types
=> Ajuste na tipagem do sendWhatsappMessagesEvent

workflow.config.type.ts
Ajuste na tipagem da configuração do chatbot.
Repositórios: isac front, back e shared types
=> Ajuste na tipagem da configuração do chatbot

icon.type.ts, workflow.config.type.ts
Ajuste na tipagem do KanbanFlagType.
Repositórios: isac front e shared types
=> Ajuste na tipagem do KanbanFlagType

workflow.config.type.ts
Criação dos observers de mudança de status da mensagem.
Repositórios: isac front, back e shared types
=> Criação dos observers de mudança de status da mensagem

step.type.ts
Atualizando ordens com ajuste no update_if_match.
Repositórios: isac front, back e shared types
=> Atualizando ordens com ajuste no update_if_match

step.type.ts
- Adicionado regra de badges nas regras das etapas
=> IVR-189 - Adicionado badges na etapa de cadastro erp e adicionado flags

workflow.config.type.ts
Adicionado referência opcional nos observers, e restrictions e trigger_observers no update-selected
=> Feature@ifm 250/assume conclude multiple cards

activity_panel.type.ts, workflow.config.type.ts
Task: [IS-30](https://ivrim.atlassian.net/browse/IS-30)
ISAC
ISAC-BACK
SHT
SHC
- Adicionado tipagem do active_panel
=> IS-30 - Painel de atividades ISAC 3.0
